### ISSUE TITLE
Not an issue: Question about Battleship and Xerox PARC Network Services

### ISSUE THREAD

**Issue by marciot** [livingcomputermuseum/ContrAlto#3]
Hello,

I am trying to get Battleship to run and have been trying to get a grasp on the network services that it relies on. I've been using the document "Miscellaneous Services (Edition 4)" by Ed Taft and the various PUP packet specs from BitSavers to try to reproduce the network services that would have been required to get it to run. So far I am able to respond to the Name Lookup Request that Battleship does when it starts, but from that point on the connection fails.

Are there any more documentation on what the Xerox PARC servers were doing, or would it be possible to run the original Name Directory Lookup software on the emulated Alto? Is that software still available or documented somewhere?

Thank you,

-- Marcio

**Comment by livingcomputermuseum** [comment]
I haven't spent too much time with Battleship in particular, but in absence of an official network name server, you can use an inter-network name instead of a symbolic one.  The syntax is "<network>#<host>#" where <network> is an octal value designating the network you're on, and <host> is your Alto's host number (i.e. your Alto's Ethernet address). 

So if you have two ContrAltos running, one with host 42 and one 43, the full inter-network names are "0#42#" and "0#43#".  Using "0" for a network number indicates that you want to talk to the local network segment (and/or don't know what network you're actually on, both of which are the case in this circumstance).  Using inter-network names in place of symbolic names is supported in most places, and should work with Battleship as far as I know.

I will also note that I am working on a complete set of Xerox IFS services (including Misc. services, CopyDisk, FTP, BreathOfLife/Boot and Mail).  I hope to have an initial release before the end of the year...

There is ample documentation, however, if you wish to keep experimenting.  The archives on Bitsavers and the CHM Xerox Alto archive (http://xeroxalto.computerhistory.org/) have everything you need.

Thanks!  Let me know if you have any questions...
- Josh

**Comment by livingcomputermuseum** [comment]
Correction (HTML got in my way when crafting the response).  

"The syntax is "##" where is an octal value designating the network you're on, and is your Alto's host number (i.e. your Alto's Ethernet address)."

should read

"The syntax is "[network]#[host]#" where [network] is an octal value designating the network you're on, and [host] is your Alto's host number (i.e. your Alto's Ethernet address)."

**Comment by marciot** [comment]
Ahhh. Great info. I'll try that. Thank you!

**Comment by marciot** [comment]
The inter-network names worked, thank you.
