### ISSUE TITLE
Building on Unix or macOS

### ISSUE THREAD

**Issue by tommythorn** [livingcomputermuseum/ContrAlto#8]
Thanks for this exciting piece of work.  Unfortunately while `readme-mono.txt` claims this builds on macOS, for someone who has never used Mono before, a few more hints would be greatly appreciated.

**Comment by livingcomputermuseum** [comment]
If you just want to use ContrAlto, you don’t need to build anything – just pick up the ContrAlto-mono.zip archive from https://github.com/livingcomputermuseum/ContrAlto/releases and follow the instructions in readme-mono.txt, particularly pay attention to section 2.0 (Requirements) so that you get the appropriate Mono runtime installed on your Mac.

If you are actually looking to build this on MacOS, starting with http://www.mono-project.com/docs/about-mono/supported-platforms/osx/ and http://www.monodevelop.com/ would be a good idea.  I can’t offer any specific advice, unfortunately – I do all ContrAlto development and building on Windows machines and test the binaries cross-platform.

Thanks,
Josh

**Comment by tommythorn** [comment]
FYI, the instructions are incorrect for modern Apple hardware; the mono from https://www.mono-project.com/download/stable/ doesn't work (it's an x86_64 version which is incompatible with the SDL2 installed with brew).  The fix is even easier: `brew install mono sdl2`
